CMPUT301F23T21/EZVault

app/src/main/java/com/example/ezvault/User.java

This PR adds a User class that contains a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) and a local value for the user's username.
It provides simple getter methods and a method `applyUserNameUpdate` which is to be used to update the local value of the `userName` field in case it is changed on the database. This class does not perform any I/O.
Any suggestions, critiques, additions, modifications, questions, etc. are appreciated.
We could use something lighter or simpler than a UUID, if that is deemed an issue.
Part of adding #1

Adds User.java exposing a User class

---

app/build.gradle.kts

Reverts CMPUT301F23T21/EZVault#25

Revert "add barcode-scanning dep (mlkit)"

---

app/src/main/java/com/example/ezvault/User.java

This PR adds a User class that contains a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) and a local value for the user's username.
It provides simple getter methods and a method applyUserNameUpdate which is to be used to update the local value of the userName field in case it is changed on the database. This class does not perform any I/O.
Any suggestions, critiques, additions, modifications, questions, etc. are appreciated.
We could use something lighter or simpler than a UUID, if that is deemed an issue.
Part of adding https://github.com/CMPUT301F23T21/EZVault/issues/1

Add User.java exposing User class

---

app/src/main/java/com/example/ezvault/Tag.java

This PR adds a tag class.
If we want some sort of pre-processing or validation in identifier we could extend the Tag class or implement another class that has that responsibility.
Part of resolving #12

Add Tag.java exposing Tag class

---

app/src/main/java/com/example/ezvault/Image.java

Adds an `Image` class
Requirements:

Add Image Class

---

app/src/main/java/com/example/ezvault/database/ItemDAO.java
app/src/main/java/com/example/ezvault/model/Item.java
app/src/main/java/com/example/ezvault/model/ItemBuilder.java

Adds a `double` value and quantity to Item.

Add value and quantity to item

---

app/src/main/java/com/example/ezvault/model/ItemList.java

This makes `ItemList` implement `List<Item>` allowing it to essentially act as a list of items.

Make ItemList implement List<Item>

---

app/src/main/java/com/example/ezvault/authentication/registration/EmailPasswordRegistrationStrategy.java
app/src/main/java/com/example/ezvault/authentication/registration/FirebaseRegistrationStrategy.java
app/src/main/java/com/example/ezvault/database/RawUserDAO.java
app/src/main/java/com/example/ezvault/database/UserService.java
app/src/main/java/com/example/ezvault/utils/TaskUtils.java

Fix registration

---

app/src/main/java/com/example/ezvault/model/ItemList.java

Add a method to ItemList that calculates the total estimated value.

Add ItemList.getTotalValue()

---

app/src/main/java/com/example/ezvault/model/Image.java
app/src/main/java/com/example/ezvault/model/Item.java
app/src/main/java/com/example/ezvault/model/ItemBuilder.java
app/src/main/java/com/example/ezvault/model/ItemList.java
app/src/main/java/com/example/ezvault/model/Tag.java
app/src/main/java/com/example/ezvault/model/User.java

Adds more documentation to the model classes.

Add Model Class Docs

---

.gitignore
app/google-services.json

This will allow builds without error on clone.
Can be merged.
Future Concerns:
#57

Add google-services.json

---

app/build.gradle.kts
app/src/main/java/com/example/ezvault/camera/CameraAction.java
app/src/main/java/com/example/ezvault/camera/GalleryAction.java
app/src/main/java/com/example/ezvault/database/FirebaseBundle.java
app/src/main/java/com/example/ezvault/database/ImageDAO.java
app/src/main/java/com/example/ezvault/database/ItemDAO.java
app/src/main/java/com/example/ezvault/model/Image.java

Implements the Image backend for communicating with the database and allows for the user to select image(s) from their gallery.

Take photos and attach photos to items

---

app/src/main/java/com/example/ezvault/database/ItemDAO.java
app/src/main/java/com/example/ezvault/database/UserService.java

Should Fix Issues with Reading Empty Lists from Firebase

(fix/db): Firebase Empty List Reading

---

app/src/main/java/com/example/ezvault/camera/CameraAction.java
app/src/main/java/com/example/ezvault/camera/GalleryAction.java
app/src/main/java/com/example/ezvault/model/ActivityTaskChunk.java

This pr changes the functionality of CameraAction so that it can now be used within fragments. Additionally, GalleryAction has been updated to work with the new abstractions.

Gallery rework

---

app/src/main/java/com/example/ezvault/model/Item.java
app/src/main/java/com/example/ezvault/model/utils/filter/ItemTagFilter.java
app/src/main/java/com/example/ezvault/model/utils/filter/MainItemFilter.java
app/src/main/java/com/example/ezvault/view/FilterFragment.java
app/src/main/java/com/example/ezvault/viewmodel/FilterViewModel.java
app/src/main/res/layout/fragment_filter.xml

feat(filtering): Filter by tags

---

app/src/main/java/com/example/ezvault/ItemAdapter.java
app/src/main/java/com/example/ezvault/MainActivity.java
app/src/main/java/com/example/ezvault/model/Item.java
app/src/main/java/com/example/ezvault/view/ItemsFragment.java
app/src/main/java/com/example/ezvault/viewmodel/ItemViewModel.java
app/src/main/res/layout/fragment_items.xml
app/src/main/res/layout/fragment_new_user.xml
app/src/main/res/layout/item_layout.xml
app/src/main/res/menu/toolbar_edit_item_menu.xml
gradle.properties

Fixed Up Version of Prior PR

---

app/src/main/java/com/example/ezvault/AddItemFragment.java
app/src/main/java/com/example/ezvault/CameraFragment.java
app/src/main/java/com/example/ezvault/EditItemDetails.java
app/src/main/java/com/example/ezvault/MainActivity.java
app/src/main/java/com/example/ezvault/PhotoAdapter.java
app/src/main/java/com/example/ezvault/ProfileFragment.java
app/src/main/java/com/example/ezvault/utils/UserManager.java
app/src/main/res/layout/fragment_camera.xml
app/src/main/res/layout/fragment_edit_item_details.xml
app/src/main/res/layout/item_layout.xml

The purpose of this branch is to improve the user experience. This was branched from delete-items so it shouldn't be merged until delete-items is merged. 
This PR so far:
- Fixes out of bounds error when deleting images.
- Integrates Corbin's UI into AddItemFragment
- Properly displays images on the Items Fragment
- Adds toasts when completing certain actions
- Updated the Camera UI and added a flash animation when a photo is taken
- Prevents the user from interacting with item fields when creating/deleting items (changed button opacity on create/save to indicate this)
- Closes #73 
WIP:
- Allow user to hide keyboard when text field loses focus
- Fix character return logic in text fields
Possible changes to be made:
- Populate items with their tags
- Remove search in bottom nav bar
Will …

App Enhancements

---

app/src/androidTest/java/com/example/ezvault/TagListTest.java

Fixes intent tests relating to tags.
Can be merged.

fix tag tests

---

app/src/main/java/com/example/ezvault/AddItemFragment.java
app/src/main/java/com/example/ezvault/EditItemDetails.java
app/src/main/java/com/example/ezvault/upcAPI.java

Refactor the barcode scanner API for the description to allow it to be used in add item and edit item.

Refactor barcode scanner and add to edit item

---

app/src/androidTest/java/com/example/ezvault/EditItemTest.java

Test 01.03.01

---

app/src/main/java/com/example/ezvault/AddItemFragment.java
app/src/main/java/com/example/ezvault/EditItemDetails.java
app/src/main/java/com/example/ezvault/LoginFragment.java
app/src/main/java/com/example/ezvault/MainActivity.java
app/src/main/java/com/example/ezvault/NewUserFragment.java
app/src/main/java/com/example/ezvault/ProfileFragment.java
app/src/main/java/com/example/ezvault/model/ItemList.java
app/src/main/java/com/example/ezvault/textwatchers/MirroredTextWatcher.java
app/src/main/java/com/example/ezvault/textwatchers/NonEmptyTextWatcher.java
app/src/main/java/com/example/ezvault/textwatchers/NumberOnlyTextWatcher.java
app/src/main/java/com/example/ezvault/textwatchers/PasswordWatcher.java
app/src/main/java/com/example/ezvault/textwatchers/TextInputWatcher.java
app/src/main/java/com/example/ezvault/utils/FragmentUtils.java
app/src/main/java/com/example/ezvault/view/ItemsFragment.java
app/src/main/res/layout/fragment_edit_item_details.xml
app/src/main/res/layout/fragment_items.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/menu/bottom_nav_menu.xml
app/src/main/res/menu/toolbar_edit_item_menu.xml
app/src/main/res/menu/toolbar_menu.xml

- Implements and closes #74 
- Simplifies updating raw user
- Adds TextWatchers for fields that need to be validated (implementation inspired by @Ziyan9).
- Updated toolbars to show correct options
- Database objects will now be validated before being uploaded
- More toasts for user actions (failed login, etc.)
* More changes to come *

App Enhancements V2

---

app/build.gradle.kts
app/src/androidTest/java/com/example/ezvault/DeleteItemTest.java

Dependent on #82.
Can be merged

Test 01.04.01 and 02.03.01

---

app/build.gradle.kts
app/src/androidTest/java/com/example/ezvault/PhotographTest.java

- Tests ability to take photo
- Tests ability to delete photo
- Tests ability to open image gallery

Created tests for photographs

---

app/src/test/java/com/example/ezvault/ItemListTest.java
app/src/test/java/com/example/ezvault/TagTest.java
app/src/test/java/com/example/ezvault/UserTest.java

Some basic unit tests

---

app/src/main/java/com/example/ezvault/view/MainActivity.java
app/src/main/java/com/example/ezvault/view/fragment/CameraFragment.java

Requests camera permissions on app launch.

Added requesting camera permissions.

---

app/src/main/java/com/example/ezvault/view/MainActivity.java
app/src/main/res/layout/fragment_profile.xml

Reverts CMPUT301F23T21/EZVault#108

Revert "Small UI changes"
